/*
 * pegasus
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing AvailableBots
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AvailableBotsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AvailableBots
        //private AvailableBots instance;

        public AvailableBotsTests()
        {
            // TODO uncomment below to create an instance of AvailableBots
            //instance = new AvailableBots();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AvailableBots
        /// </summary>
        [Fact]
        public void AvailableBotsInstanceTest()
        {
            // TODO uncomment below to test "IsType" AvailableBots
            //Assert.IsType<AvailableBots>(instance);
        }

        /// <summary>
        /// Test the property 'Bots'
        /// </summary>
        [Fact]
        public void BotsTest()
        {
            // TODO unit test for the property 'Bots'
        }
    }
}
