/*
 * pegasus
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing BotInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BotInfoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for BotInfo
        //private BotInfo instance;

        public BotInfoTests()
        {
            // TODO uncomment below to create an instance of BotInfo
            //instance = new BotInfo();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BotInfo
        /// </summary>
        [Fact]
        public void BotInfoInstanceTest()
        {
            // TODO uncomment below to test "IsType" BotInfo
            //Assert.IsType<BotInfo>(instance);
        }

        /// <summary>
        /// Test the property 'Figure'
        /// </summary>
        [Fact]
        public void FigureTest()
        {
            // TODO unit test for the property 'Figure'
        }

        /// <summary>
        /// Test the property 'Gender'
        /// </summary>
        [Fact]
        public void GenderTest()
        {
            // TODO unit test for the property 'Gender'
        }

        /// <summary>
        /// Test the property 'Motto'
        /// </summary>
        [Fact]
        public void MottoTest()
        {
            // TODO unit test for the property 'Motto'
        }

        /// <summary>
        /// Test the property 'SsoTicket'
        /// </summary>
        [Fact]
        public void SsoTicketTest()
        {
            // TODO unit test for the property 'SsoTicket'
        }

        /// <summary>
        /// Test the property 'UserId'
        /// </summary>
        [Fact]
        public void UserIdTest()
        {
            // TODO unit test for the property 'UserId'
        }

        /// <summary>
        /// Test the property 'Username'
        /// </summary>
        [Fact]
        public void UsernameTest()
        {
            // TODO unit test for the property 'Username'
        }
    }
}
