/*
 * pegasus
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing BotsRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BotsRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for BotsRequest
        //private BotsRequest instance;

        public BotsRequestTests()
        {
            // TODO uncomment below to create an instance of BotsRequest
            //instance = new BotsRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BotsRequest
        /// </summary>
        [Fact]
        public void BotsRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" BotsRequest
            //Assert.IsType<BotsRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Hotel'
        /// </summary>
        [Fact]
        public void HotelTest()
        {
            // TODO unit test for the property 'Hotel'
        }
    }
}
