/**
 * pegasus
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { BotInfo } from '../models/BotInfo';
import { HttpFile } from '../http/http';

export class AvailableBots {
    'bots'?: Array<BotInfo> | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "bots",
            "baseName": "bots",
            "type": "Array<BotInfo>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AvailableBots.attributeTypeMap;
    }

    public constructor() {
    }
}

