/*
 * pegasus
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// BotsRequest
    /// </summary>
    [DataContract(Name = "BotsRequest")]
    public partial class BotsRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BotsRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected BotsRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="BotsRequest" /> class.
        /// </summary>
        /// <param name="hotel">hotel (required).</param>
        public BotsRequest(string hotel = default(string))
        {
            // to ensure "hotel" is required (not null)
            if (hotel == null)
            {
                throw new ArgumentNullException("hotel is a required property for BotsRequest and cannot be null");
            }
            this.Hotel = hotel;
        }

        /// <summary>
        /// Gets or Sets Hotel
        /// </summary>
        [DataMember(Name = "hotel", IsRequired = true, EmitDefaultValue = true)]
        public string Hotel { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class BotsRequest {\n");
            sb.Append("  Hotel: ").Append(Hotel).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
