/*
 * pegasus
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;
// uncomment below to import models
//using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Test.Api
{
    /// <summary>
    ///  Class for testing BotApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class BotApiTests : IDisposable
    {
        private BotApi instance;

        public BotApiTests()
        {
            instance = new BotApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BotApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' BotApi
            //Assert.IsType<BotApi>(instance);
        }

        /// <summary>
        /// Test Index
        /// </summary>
        [Fact]
        public void IndexTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //BotsRequest botsRequest = null;
            //var response = instance.Index(botsRequest);
            //Assert.IsType<AvailableBots>(response);
        }

        /// <summary>
        /// Test Show
        /// </summary>
        [Fact]
        public void ShowTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string ticket = null;
            //ShowBotRequest showBotRequest = null;
            //var response = instance.Show(ticket, showBotRequest);
            //Assert.IsType<AvailableBots>(response);
        }
    }
}
