# coding: utf-8

# flake8: noqa
"""
    pegasus

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from openapi_client.models.available_bots import AvailableBots
from openapi_client.models.bot_info import BotInfo
from openapi_client.models.bots_request import BotsRequest
from openapi_client.models.bulk_update_response import BulkUpdateResponse
from openapi_client.models.show_bot_request import ShowBotRequest
