# coding: utf-8

"""
    pegasus

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.bots_request import BotsRequest

class TestBotsRequest(unittest.TestCase):
    """BotsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BotsRequest:
        """Test BotsRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BotsRequest`
        """
        model = BotsRequest()
        if include_optional:
            return BotsRequest(
                hotel = ''
            )
        else:
            return BotsRequest(
                hotel = '',
        )
        """

    def testBotsRequest(self):
        """Test BotsRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
