# coding: utf-8

"""
    pegasus

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.bot_controller_api import BotControllerApi


class TestBotControllerApi(unittest.TestCase):
    """BotControllerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BotControllerApi()

    def tearDown(self) -> None:
        pass

    def test_index(self) -> None:
        """Test case for index

        """
        pass

    def test_show(self) -> None:
        """Test case for show

        """
        pass


if __name__ == '__main__':
    unittest.main()
