# coding: utf-8

"""
    pegasus

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.bot_info import BotInfo

class TestBotInfo(unittest.TestCase):
    """BotInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BotInfo:
        """Test BotInfo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BotInfo`
        """
        model = BotInfo()
        if include_optional:
            return BotInfo(
                figure = '',
                gender = '',
                motto = '',
                sso_ticket = '',
                user_id = 0,
                username = ''
            )
        else:
            return BotInfo(
                figure = '',
                gender = '',
                motto = '',
                sso_ticket = '',
                user_id = 0,
                username = '',
        )
        """

    def testBotInfo(self):
        """Test BotInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
