# coding: utf-8

"""
    pegasus

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.available_bots import AvailableBots

class TestAvailableBots(unittest.TestCase):
    """AvailableBots unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AvailableBots:
        """Test AvailableBots
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AvailableBots`
        """
        model = AvailableBots()
        if include_optional:
            return AvailableBots(
                bots = [
                    openapi_client.models.bot_info.BotInfo(
                        figure = '', 
                        gender = '', 
                        motto = '', 
                        sso_ticket = '', 
                        user_id = 0, 
                        username = '', )
                    ]
            )
        else:
            return AvailableBots(
        )
        """

    def testAvailableBots(self):
        """Test AvailableBots"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
