# coding: utf-8

# flake8: noqa

"""
    pegasus

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# import apis into sdk package
from openapi_client.api.bot_api import BotApi
from openapi_client.api.bot_controller_api import BotControllerApi

# import ApiClient
from openapi_client.api_response import ApiResponse
from openapi_client.api_client import ApiClient
from openapi_client.configuration import Configuration
from openapi_client.exceptions import OpenApiException
from openapi_client.exceptions import ApiTypeError
from openapi_client.exceptions import ApiValueError
from openapi_client.exceptions import ApiKeyError
from openapi_client.exceptions import ApiAttributeError
from openapi_client.exceptions import ApiException

# import models into sdk package
from openapi_client.models.available_bots import AvailableBots
from openapi_client.models.bot_info import BotInfo
from openapi_client.models.bots_request import BotsRequest
from openapi_client.models.bulk_update_response import BulkUpdateResponse
from openapi_client.models.show_bot_request import ShowBotRequest
